/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProgrammesRouteImport } from './routes/programmes'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as FinanceReadinessRouteImport } from './routes/finance-readiness'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademyIndexRouteImport } from './routes/academy.index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as AcademyCoursesProfessionalsAiEdgeRouteImport } from './routes/academy.courses.professionals-ai-edge'
import { Route as AcademyCoursesIcss20EntrepreneurshipRouteImport } from './routes/academy.courses.icss-2-0-entrepreneurship'
import { Route as AcademyCoursesFinanceReadinessMsmesRouteImport } from './routes/academy.courses.finance-readiness-msmes'
import { Route as AcademyCoursesAiToolsSmallBusinessesRouteImport } from './routes/academy.courses.ai-tools-small-businesses'
import { Route as AuthenticatedAdminWaitlistRouteImport } from './routes/_authenticated.admin.waitlist'
import { Route as AuthenticatedAdminVideoStudioRouteImport } from './routes/_authenticated.admin.video-studio'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated.admin.payments'
import { Route as AuthenticatedAdminEnrolmentsRouteImport } from './routes/_authenticated.admin.enrolments'
import { Route as AuthenticatedAdminCoursesRouteImport } from './routes/_authenticated.admin.courses'
import { Route as AuthenticatedAdminCouponsRouteImport } from './routes/_authenticated.admin.coupons'
import { Route as AuthenticatedAdminCertificatesRouteImport } from './routes/_authenticated.admin.certificates'
import { Route as AuthenticatedAdminAssessmentsRouteImport } from './routes/_authenticated.admin.assessments'
import { Route as AuthenticatedAcademyReferralsRouteImport } from './routes/_authenticated.academy.referrals'
import { Route as AuthenticatedAcademyReceiptRouteImport } from './routes/_authenticated.academy.receipt'
import { Route as AuthenticatedAcademyDashboardRouteImport } from './routes/_authenticated.academy.dashboard'
import { Route as AuthenticatedAcademyBadgesRouteImport } from './routes/_authenticated.academy.badges'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack.webhook'
import { Route as ApiPublicPaystackVerifyRouteImport } from './routes/api/public/paystack.verify'
import { Route as AuthenticatedAcademyDashboardCoursesSlugRouteImport } from './routes/_authenticated.academy.dashboard.courses.$slug'
import { Route as AuthenticatedAcademyDashboardCoursesSlugLeaderboardRouteImport } from './routes/_authenticated.academy.dashboard.courses.$slug.leaderboard'
import { Route as AuthenticatedAcademyDashboardCoursesSlugAssessmentsRouteImport } from './routes/_authenticated.academy.dashboard.courses.$slug.assessments'
import { Route as AuthenticatedAcademyDashboardCoursesSlugQuizQuizIdRouteImport } from './routes/_authenticated.academy.dashboard.courses.$slug.quiz.$quizId'
import { Route as AuthenticatedAcademyDashboardCoursesSlugAssignmentAssignmentIdRouteImport } from './routes/_authenticated.academy.dashboard.courses.$slug.assignment.$assignmentId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesRoute = ProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceReadinessRoute = FinanceReadinessRouteImport.update({
  id: '/finance-readiness',
  path: '/finance-readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyIndexRoute = AcademyIndexRouteImport.update({
  id: '/academy/',
  path: '/academy/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AcademyCoursesProfessionalsAiEdgeRoute =
  AcademyCoursesProfessionalsAiEdgeRouteImport.update({
    id: '/academy/courses/professionals-ai-edge',
    path: '/academy/courses/professionals-ai-edge',
    getParentRoute: () => rootRouteImport,
  } as any)
const AcademyCoursesIcss20EntrepreneurshipRoute =
  AcademyCoursesIcss20EntrepreneurshipRouteImport.update({
    id: '/academy/courses/icss-2-0-entrepreneurship',
    path: '/academy/courses/icss-2-0-entrepreneurship',
    getParentRoute: () => rootRouteImport,
  } as any)
const AcademyCoursesFinanceReadinessMsmesRoute =
  AcademyCoursesFinanceReadinessMsmesRouteImport.update({
    id: '/academy/courses/finance-readiness-msmes',
    path: '/academy/courses/finance-readiness-msmes',
    getParentRoute: () => rootRouteImport,
  } as any)
const AcademyCoursesAiToolsSmallBusinessesRoute =
  AcademyCoursesAiToolsSmallBusinessesRouteImport.update({
    id: '/academy/courses/ai-tools-small-businesses',
    path: '/academy/courses/ai-tools-small-businesses',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminWaitlistRoute =
  AuthenticatedAdminWaitlistRouteImport.update({
    id: '/waitlist',
    path: '/waitlist',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminVideoStudioRoute =
  AuthenticatedAdminVideoStudioRouteImport.update({
    id: '/video-studio',
    path: '/video-studio',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEnrolmentsRoute =
  AuthenticatedAdminEnrolmentsRouteImport.update({
    id: '/enrolments',
    path: '/enrolments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCoursesRoute =
  AuthenticatedAdminCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCouponsRoute =
  AuthenticatedAdminCouponsRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCertificatesRoute =
  AuthenticatedAdminCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAssessmentsRoute =
  AuthenticatedAdminAssessmentsRouteImport.update({
    id: '/assessments',
    path: '/assessments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAcademyReferralsRoute =
  AuthenticatedAcademyReferralsRouteImport.update({
    id: '/academy/referrals',
    path: '/academy/referrals',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAcademyReceiptRoute =
  AuthenticatedAcademyReceiptRouteImport.update({
    id: '/academy/receipt',
    path: '/academy/receipt',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAcademyDashboardRoute =
  AuthenticatedAcademyDashboardRouteImport.update({
    id: '/academy/dashboard',
    path: '/academy/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAcademyBadgesRoute =
  AuthenticatedAcademyBadgesRouteImport.update({
    id: '/academy/badges',
    path: '/academy/badges',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack/webhook',
    path: '/api/public/paystack/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaystackVerifyRoute = ApiPublicPaystackVerifyRouteImport.update({
  id: '/api/public/paystack/verify',
  path: '/api/public/paystack/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAcademyDashboardCoursesSlugRoute =
  AuthenticatedAcademyDashboardCoursesSlugRouteImport.update({
    id: '/courses/$slug',
    path: '/courses/$slug',
    getParentRoute: () => AuthenticatedAcademyDashboardRoute,
  } as any)
const AuthenticatedAcademyDashboardCoursesSlugLeaderboardRoute =
  AuthenticatedAcademyDashboardCoursesSlugLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedAcademyDashboardCoursesSlugRoute,
  } as any)
const AuthenticatedAcademyDashboardCoursesSlugAssessmentsRoute =
  AuthenticatedAcademyDashboardCoursesSlugAssessmentsRouteImport.update({
    id: '/assessments',
    path: '/assessments',
    getParentRoute: () => AuthenticatedAcademyDashboardCoursesSlugRoute,
  } as any)
const AuthenticatedAcademyDashboardCoursesSlugQuizQuizIdRoute =
  AuthenticatedAcademyDashboardCoursesSlugQuizQuizIdRouteImport.update({
    id: '/quiz/$quizId',
    path: '/quiz/$quizId',
    getParentRoute: () => AuthenticatedAcademyDashboardCoursesSlugRoute,
  } as any)
const AuthenticatedAcademyDashboardCoursesSlugAssignmentAssignmentIdRoute =
  AuthenticatedAcademyDashboardCoursesSlugAssignmentAssignmentIdRouteImport.update(
    {
      id: '/assignment/$assignmentId',
      path: '/assignment/$assignmentId',
      getParentRoute: () => AuthenticatedAcademyDashboardCoursesSlugRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/finance-readiness': typeof FinanceReadinessRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/programmes': typeof ProgrammesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/academy/': typeof AcademyIndexRoute
  '/academy/badges': typeof AuthenticatedAcademyBadgesRoute
  '/academy/dashboard': typeof AuthenticatedAcademyDashboardRouteWithChildren
  '/academy/receipt': typeof AuthenticatedAcademyReceiptRoute
  '/academy/referrals': typeof AuthenticatedAcademyReferralsRoute
  '/admin/assessments': typeof AuthenticatedAdminAssessmentsRoute
  '/admin/certificates': typeof AuthenticatedAdminCertificatesRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/enrolments': typeof AuthenticatedAdminEnrolmentsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/video-studio': typeof AuthenticatedAdminVideoStudioRoute
  '/admin/waitlist': typeof AuthenticatedAdminWaitlistRoute
  '/academy/courses/ai-tools-small-businesses': typeof AcademyCoursesAiToolsSmallBusinessesRoute
  '/academy/courses/finance-readiness-msmes': typeof AcademyCoursesFinanceReadinessMsmesRoute
  '/academy/courses/icss-2-0-entrepreneurship': typeof AcademyCoursesIcss20EntrepreneurshipRoute
  '/academy/courses/professionals-ai-edge': typeof AcademyCoursesProfessionalsAiEdgeRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/paystack/verify': typeof ApiPublicPaystackVerifyRoute
  '/api/public/paystack/webhook': typeof ApiPublicPaystackWebhookRoute
  '/academy/dashboard/courses/$slug': typeof AuthenticatedAcademyDashboardCoursesSlugRouteWithChildren
  '/academy/dashboard/courses/$slug/assessments': typeof AuthenticatedAcademyDashboardCoursesSlugAssessmentsRoute
  '/academy/dashboard/courses/$slug/leaderboard': typeof AuthenticatedAcademyDashboardCoursesSlugLeaderboardRoute
  '/academy/dashboard/courses/$slug/assignment/$assignmentId': typeof AuthenticatedAcademyDashboardCoursesSlugAssignmentAssignmentIdRoute
  '/academy/dashboard/courses/$slug/quiz/$quizId': typeof AuthenticatedAcademyDashboardCoursesSlugQuizQuizIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/finance-readiness': typeof FinanceReadinessRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/programmes': typeof ProgrammesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/academy': typeof AcademyIndexRoute
  '/academy/badges': typeof AuthenticatedAcademyBadgesRoute
  '/academy/dashboard': typeof AuthenticatedAcademyDashboardRouteWithChildren
  '/academy/receipt': typeof AuthenticatedAcademyReceiptRoute
  '/academy/referrals': typeof AuthenticatedAcademyReferralsRoute
  '/admin/assessments': typeof AuthenticatedAdminAssessmentsRoute
  '/admin/certificates': typeof AuthenticatedAdminCertificatesRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/enrolments': typeof AuthenticatedAdminEnrolmentsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/video-studio': typeof AuthenticatedAdminVideoStudioRoute
  '/admin/waitlist': typeof AuthenticatedAdminWaitlistRoute
  '/academy/courses/ai-tools-small-businesses': typeof AcademyCoursesAiToolsSmallBusinessesRoute
  '/academy/courses/finance-readiness-msmes': typeof AcademyCoursesFinanceReadinessMsmesRoute
  '/academy/courses/icss-2-0-entrepreneurship': typeof AcademyCoursesIcss20EntrepreneurshipRoute
  '/academy/courses/professionals-ai-edge': typeof AcademyCoursesProfessionalsAiEdgeRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/paystack/verify': typeof ApiPublicPaystackVerifyRoute
  '/api/public/paystack/webhook': typeof ApiPublicPaystackWebhookRoute
  '/academy/dashboard/courses/$slug': typeof AuthenticatedAcademyDashboardCoursesSlugRouteWithChildren
  '/academy/dashboard/courses/$slug/assessments': typeof AuthenticatedAcademyDashboardCoursesSlugAssessmentsRoute
  '/academy/dashboard/courses/$slug/leaderboard': typeof AuthenticatedAcademyDashboardCoursesSlugLeaderboardRoute
  '/academy/dashboard/courses/$slug/assignment/$assignmentId': typeof AuthenticatedAcademyDashboardCoursesSlugAssignmentAssignmentIdRoute
  '/academy/dashboard/courses/$slug/quiz/$quizId': typeof AuthenticatedAcademyDashboardCoursesSlugQuizQuizIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/finance-readiness': typeof FinanceReadinessRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/programmes': typeof ProgrammesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/academy/': typeof AcademyIndexRoute
  '/_authenticated/academy/badges': typeof AuthenticatedAcademyBadgesRoute
  '/_authenticated/academy/dashboard': typeof AuthenticatedAcademyDashboardRouteWithChildren
  '/_authenticated/academy/receipt': typeof AuthenticatedAcademyReceiptRoute
  '/_authenticated/academy/referrals': typeof AuthenticatedAcademyReferralsRoute
  '/_authenticated/admin/assessments': typeof AuthenticatedAdminAssessmentsRoute
  '/_authenticated/admin/certificates': typeof AuthenticatedAdminCertificatesRoute
  '/_authenticated/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/_authenticated/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/_authenticated/admin/enrolments': typeof AuthenticatedAdminEnrolmentsRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/video-studio': typeof AuthenticatedAdminVideoStudioRoute
  '/_authenticated/admin/waitlist': typeof AuthenticatedAdminWaitlistRoute
  '/academy/courses/ai-tools-small-businesses': typeof AcademyCoursesAiToolsSmallBusinessesRoute
  '/academy/courses/finance-readiness-msmes': typeof AcademyCoursesFinanceReadinessMsmesRoute
  '/academy/courses/icss-2-0-entrepreneurship': typeof AcademyCoursesIcss20EntrepreneurshipRoute
  '/academy/courses/professionals-ai-edge': typeof AcademyCoursesProfessionalsAiEdgeRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/paystack/verify': typeof ApiPublicPaystackVerifyRoute
  '/api/public/paystack/webhook': typeof ApiPublicPaystackWebhookRoute
  '/_authenticated/academy/dashboard/courses/$slug': typeof AuthenticatedAcademyDashboardCoursesSlugRouteWithChildren
  '/_authenticated/academy/dashboard/courses/$slug/assessments': typeof AuthenticatedAcademyDashboardCoursesSlugAssessmentsRoute
  '/_authenticated/academy/dashboard/courses/$slug/leaderboard': typeof AuthenticatedAcademyDashboardCoursesSlugLeaderboardRoute
  '/_authenticated/academy/dashboard/courses/$slug/assignment/$assignmentId': typeof AuthenticatedAcademyDashboardCoursesSlugAssignmentAssignmentIdRoute
  '/_authenticated/academy/dashboard/courses/$slug/quiz/$quizId': typeof AuthenticatedAcademyDashboardCoursesSlugQuizQuizIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/finance-readiness'
    | '/insights'
    | '/login'
    | '/privacy'
    | '/programmes'
    | '/reset-password'
    | '/services'
    | '/signup'
    | '/terms'
    | '/admin'
    | '/academy/'
    | '/academy/badges'
    | '/academy/dashboard'
    | '/academy/receipt'
    | '/academy/referrals'
    | '/admin/assessments'
    | '/admin/certificates'
    | '/admin/coupons'
    | '/admin/courses'
    | '/admin/enrolments'
    | '/admin/payments'
    | '/admin/video-studio'
    | '/admin/waitlist'
    | '/academy/courses/ai-tools-small-businesses'
    | '/academy/courses/finance-readiness-msmes'
    | '/academy/courses/icss-2-0-entrepreneurship'
    | '/academy/courses/professionals-ai-edge'
    | '/admin/'
    | '/api/public/paystack/verify'
    | '/api/public/paystack/webhook'
    | '/academy/dashboard/courses/$slug'
    | '/academy/dashboard/courses/$slug/assessments'
    | '/academy/dashboard/courses/$slug/leaderboard'
    | '/academy/dashboard/courses/$slug/assignment/$assignmentId'
    | '/academy/dashboard/courses/$slug/quiz/$quizId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/finance-readiness'
    | '/insights'
    | '/login'
    | '/privacy'
    | '/programmes'
    | '/reset-password'
    | '/services'
    | '/signup'
    | '/terms'
    | '/academy'
    | '/academy/badges'
    | '/academy/dashboard'
    | '/academy/receipt'
    | '/academy/referrals'
    | '/admin/assessments'
    | '/admin/certificates'
    | '/admin/coupons'
    | '/admin/courses'
    | '/admin/enrolments'
    | '/admin/payments'
    | '/admin/video-studio'
    | '/admin/waitlist'
    | '/academy/courses/ai-tools-small-businesses'
    | '/academy/courses/finance-readiness-msmes'
    | '/academy/courses/icss-2-0-entrepreneurship'
    | '/academy/courses/professionals-ai-edge'
    | '/admin'
    | '/api/public/paystack/verify'
    | '/api/public/paystack/webhook'
    | '/academy/dashboard/courses/$slug'
    | '/academy/dashboard/courses/$slug/assessments'
    | '/academy/dashboard/courses/$slug/leaderboard'
    | '/academy/dashboard/courses/$slug/assignment/$assignmentId'
    | '/academy/dashboard/courses/$slug/quiz/$quizId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/contact'
    | '/finance-readiness'
    | '/insights'
    | '/login'
    | '/privacy'
    | '/programmes'
    | '/reset-password'
    | '/services'
    | '/signup'
    | '/terms'
    | '/_authenticated/admin'
    | '/academy/'
    | '/_authenticated/academy/badges'
    | '/_authenticated/academy/dashboard'
    | '/_authenticated/academy/receipt'
    | '/_authenticated/academy/referrals'
    | '/_authenticated/admin/assessments'
    | '/_authenticated/admin/certificates'
    | '/_authenticated/admin/coupons'
    | '/_authenticated/admin/courses'
    | '/_authenticated/admin/enrolments'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/video-studio'
    | '/_authenticated/admin/waitlist'
    | '/academy/courses/ai-tools-small-businesses'
    | '/academy/courses/finance-readiness-msmes'
    | '/academy/courses/icss-2-0-entrepreneurship'
    | '/academy/courses/professionals-ai-edge'
    | '/_authenticated/admin/'
    | '/api/public/paystack/verify'
    | '/api/public/paystack/webhook'
    | '/_authenticated/academy/dashboard/courses/$slug'
    | '/_authenticated/academy/dashboard/courses/$slug/assessments'
    | '/_authenticated/academy/dashboard/courses/$slug/leaderboard'
    | '/_authenticated/academy/dashboard/courses/$slug/assignment/$assignmentId'
    | '/_authenticated/academy/dashboard/courses/$slug/quiz/$quizId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FinanceReadinessRoute: typeof FinanceReadinessRoute
  InsightsRoute: typeof InsightsRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgrammesRoute: typeof ProgrammesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  AcademyIndexRoute: typeof AcademyIndexRoute
  AcademyCoursesAiToolsSmallBusinessesRoute: typeof AcademyCoursesAiToolsSmallBusinessesRoute
  AcademyCoursesFinanceReadinessMsmesRoute: typeof AcademyCoursesFinanceReadinessMsmesRoute
  AcademyCoursesIcss20EntrepreneurshipRoute: typeof AcademyCoursesIcss20EntrepreneurshipRoute
  AcademyCoursesProfessionalsAiEdgeRoute: typeof AcademyCoursesProfessionalsAiEdgeRoute
  ApiPublicPaystackVerifyRoute: typeof ApiPublicPaystackVerifyRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes': {
      id: '/programmes'
      path: '/programmes'
      fullPath: '/programmes'
      preLoaderRoute: typeof ProgrammesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance-readiness': {
      id: '/finance-readiness'
      path: '/finance-readiness'
      fullPath: '/finance-readiness'
      preLoaderRoute: typeof FinanceReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/': {
      id: '/academy/'
      path: '/academy'
      fullPath: '/academy/'
      preLoaderRoute: typeof AcademyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/academy/courses/professionals-ai-edge': {
      id: '/academy/courses/professionals-ai-edge'
      path: '/academy/courses/professionals-ai-edge'
      fullPath: '/academy/courses/professionals-ai-edge'
      preLoaderRoute: typeof AcademyCoursesProfessionalsAiEdgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/courses/icss-2-0-entrepreneurship': {
      id: '/academy/courses/icss-2-0-entrepreneurship'
      path: '/academy/courses/icss-2-0-entrepreneurship'
      fullPath: '/academy/courses/icss-2-0-entrepreneurship'
      preLoaderRoute: typeof AcademyCoursesIcss20EntrepreneurshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/courses/finance-readiness-msmes': {
      id: '/academy/courses/finance-readiness-msmes'
      path: '/academy/courses/finance-readiness-msmes'
      fullPath: '/academy/courses/finance-readiness-msmes'
      preLoaderRoute: typeof AcademyCoursesFinanceReadinessMsmesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/courses/ai-tools-small-businesses': {
      id: '/academy/courses/ai-tools-small-businesses'
      path: '/academy/courses/ai-tools-small-businesses'
      fullPath: '/academy/courses/ai-tools-small-businesses'
      preLoaderRoute: typeof AcademyCoursesAiToolsSmallBusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/waitlist': {
      id: '/_authenticated/admin/waitlist'
      path: '/waitlist'
      fullPath: '/admin/waitlist'
      preLoaderRoute: typeof AuthenticatedAdminWaitlistRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/video-studio': {
      id: '/_authenticated/admin/video-studio'
      path: '/video-studio'
      fullPath: '/admin/video-studio'
      preLoaderRoute: typeof AuthenticatedAdminVideoStudioRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/enrolments': {
      id: '/_authenticated/admin/enrolments'
      path: '/enrolments'
      fullPath: '/admin/enrolments'
      preLoaderRoute: typeof AuthenticatedAdminEnrolmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/courses': {
      id: '/_authenticated/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthenticatedAdminCoursesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/coupons': {
      id: '/_authenticated/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AuthenticatedAdminCouponsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/certificates': {
      id: '/_authenticated/admin/certificates'
      path: '/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AuthenticatedAdminCertificatesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/assessments': {
      id: '/_authenticated/admin/assessments'
      path: '/assessments'
      fullPath: '/admin/assessments'
      preLoaderRoute: typeof AuthenticatedAdminAssessmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/academy/referrals': {
      id: '/_authenticated/academy/referrals'
      path: '/academy/referrals'
      fullPath: '/academy/referrals'
      preLoaderRoute: typeof AuthenticatedAcademyReferralsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/academy/receipt': {
      id: '/_authenticated/academy/receipt'
      path: '/academy/receipt'
      fullPath: '/academy/receipt'
      preLoaderRoute: typeof AuthenticatedAcademyReceiptRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/academy/dashboard': {
      id: '/_authenticated/academy/dashboard'
      path: '/academy/dashboard'
      fullPath: '/academy/dashboard'
      preLoaderRoute: typeof AuthenticatedAcademyDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/academy/badges': {
      id: '/_authenticated/academy/badges'
      path: '/academy/badges'
      fullPath: '/academy/badges'
      preLoaderRoute: typeof AuthenticatedAcademyBadgesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/paystack/webhook': {
      id: '/api/public/paystack/webhook'
      path: '/api/public/paystack/webhook'
      fullPath: '/api/public/paystack/webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paystack/verify': {
      id: '/api/public/paystack/verify'
      path: '/api/public/paystack/verify'
      fullPath: '/api/public/paystack/verify'
      preLoaderRoute: typeof ApiPublicPaystackVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/academy/dashboard/courses/$slug': {
      id: '/_authenticated/academy/dashboard/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/academy/dashboard/courses/$slug'
      preLoaderRoute: typeof AuthenticatedAcademyDashboardCoursesSlugRouteImport
      parentRoute: typeof AuthenticatedAcademyDashboardRoute
    }
    '/_authenticated/academy/dashboard/courses/$slug/leaderboard': {
      id: '/_authenticated/academy/dashboard/courses/$slug/leaderboard'
      path: '/leaderboard'
      fullPath: '/academy/dashboard/courses/$slug/leaderboard'
      preLoaderRoute: typeof AuthenticatedAcademyDashboardCoursesSlugLeaderboardRouteImport
      parentRoute: typeof AuthenticatedAcademyDashboardCoursesSlugRoute
    }
    '/_authenticated/academy/dashboard/courses/$slug/assessments': {
      id: '/_authenticated/academy/dashboard/courses/$slug/assessments'
      path: '/assessments'
      fullPath: '/academy/dashboard/courses/$slug/assessments'
      preLoaderRoute: typeof AuthenticatedAcademyDashboardCoursesSlugAssessmentsRouteImport
      parentRoute: typeof AuthenticatedAcademyDashboardCoursesSlugRoute
    }
    '/_authenticated/academy/dashboard/courses/$slug/quiz/$quizId': {
      id: '/_authenticated/academy/dashboard/courses/$slug/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/academy/dashboard/courses/$slug/quiz/$quizId'
      preLoaderRoute: typeof AuthenticatedAcademyDashboardCoursesSlugQuizQuizIdRouteImport
      parentRoute: typeof AuthenticatedAcademyDashboardCoursesSlugRoute
    }
    '/_authenticated/academy/dashboard/courses/$slug/assignment/$assignmentId': {
      id: '/_authenticated/academy/dashboard/courses/$slug/assignment/$assignmentId'
      path: '/assignment/$assignmentId'
      fullPath: '/academy/dashboard/courses/$slug/assignment/$assignmentId'
      preLoaderRoute: typeof AuthenticatedAcademyDashboardCoursesSlugAssignmentAssignmentIdRouteImport
      parentRoute: typeof AuthenticatedAcademyDashboardCoursesSlugRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAssessmentsRoute: typeof AuthenticatedAdminAssessmentsRoute
  AuthenticatedAdminCertificatesRoute: typeof AuthenticatedAdminCertificatesRoute
  AuthenticatedAdminCouponsRoute: typeof AuthenticatedAdminCouponsRoute
  AuthenticatedAdminCoursesRoute: typeof AuthenticatedAdminCoursesRoute
  AuthenticatedAdminEnrolmentsRoute: typeof AuthenticatedAdminEnrolmentsRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminVideoStudioRoute: typeof AuthenticatedAdminVideoStudioRoute
  AuthenticatedAdminWaitlistRoute: typeof AuthenticatedAdminWaitlistRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAssessmentsRoute: AuthenticatedAdminAssessmentsRoute,
  AuthenticatedAdminCertificatesRoute: AuthenticatedAdminCertificatesRoute,
  AuthenticatedAdminCouponsRoute: AuthenticatedAdminCouponsRoute,
  AuthenticatedAdminCoursesRoute: AuthenticatedAdminCoursesRoute,
  AuthenticatedAdminEnrolmentsRoute: AuthenticatedAdminEnrolmentsRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminVideoStudioRoute: AuthenticatedAdminVideoStudioRoute,
  AuthenticatedAdminWaitlistRoute: AuthenticatedAdminWaitlistRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAcademyDashboardCoursesSlugRouteChildren {
  AuthenticatedAcademyDashboardCoursesSlugAssessmentsRoute: typeof AuthenticatedAcademyDashboardCoursesSlugAssessmentsRoute
  AuthenticatedAcademyDashboardCoursesSlugLeaderboardRoute: typeof AuthenticatedAcademyDashboardCoursesSlugLeaderboardRoute
  AuthenticatedAcademyDashboardCoursesSlugAssignmentAssignmentIdRoute: typeof AuthenticatedAcademyDashboardCoursesSlugAssignmentAssignmentIdRoute
  AuthenticatedAcademyDashboardCoursesSlugQuizQuizIdRoute: typeof AuthenticatedAcademyDashboardCoursesSlugQuizQuizIdRoute
}

const AuthenticatedAcademyDashboardCoursesSlugRouteChildren: AuthenticatedAcademyDashboardCoursesSlugRouteChildren =
  {
    AuthenticatedAcademyDashboardCoursesSlugAssessmentsRoute:
      AuthenticatedAcademyDashboardCoursesSlugAssessmentsRoute,
    AuthenticatedAcademyDashboardCoursesSlugLeaderboardRoute:
      AuthenticatedAcademyDashboardCoursesSlugLeaderboardRoute,
    AuthenticatedAcademyDashboardCoursesSlugAssignmentAssignmentIdRoute:
      AuthenticatedAcademyDashboardCoursesSlugAssignmentAssignmentIdRoute,
    AuthenticatedAcademyDashboardCoursesSlugQuizQuizIdRoute:
      AuthenticatedAcademyDashboardCoursesSlugQuizQuizIdRoute,
  }

const AuthenticatedAcademyDashboardCoursesSlugRouteWithChildren =
  AuthenticatedAcademyDashboardCoursesSlugRoute._addFileChildren(
    AuthenticatedAcademyDashboardCoursesSlugRouteChildren,
  )

interface AuthenticatedAcademyDashboardRouteChildren {
  AuthenticatedAcademyDashboardCoursesSlugRoute: typeof AuthenticatedAcademyDashboardCoursesSlugRouteWithChildren
}

const AuthenticatedAcademyDashboardRouteChildren: AuthenticatedAcademyDashboardRouteChildren =
  {
    AuthenticatedAcademyDashboardCoursesSlugRoute:
      AuthenticatedAcademyDashboardCoursesSlugRouteWithChildren,
  }

const AuthenticatedAcademyDashboardRouteWithChildren =
  AuthenticatedAcademyDashboardRoute._addFileChildren(
    AuthenticatedAcademyDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAcademyBadgesRoute: typeof AuthenticatedAcademyBadgesRoute
  AuthenticatedAcademyDashboardRoute: typeof AuthenticatedAcademyDashboardRouteWithChildren
  AuthenticatedAcademyReceiptRoute: typeof AuthenticatedAcademyReceiptRoute
  AuthenticatedAcademyReferralsRoute: typeof AuthenticatedAcademyReferralsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAcademyBadgesRoute: AuthenticatedAcademyBadgesRoute,
  AuthenticatedAcademyDashboardRoute:
    AuthenticatedAcademyDashboardRouteWithChildren,
  AuthenticatedAcademyReceiptRoute: AuthenticatedAcademyReceiptRoute,
  AuthenticatedAcademyReferralsRoute: AuthenticatedAcademyReferralsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FinanceReadinessRoute: FinanceReadinessRoute,
  InsightsRoute: InsightsRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ProgrammesRoute: ProgrammesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  AcademyIndexRoute: AcademyIndexRoute,
  AcademyCoursesAiToolsSmallBusinessesRoute:
    AcademyCoursesAiToolsSmallBusinessesRoute,
  AcademyCoursesFinanceReadinessMsmesRoute:
    AcademyCoursesFinanceReadinessMsmesRoute,
  AcademyCoursesIcss20EntrepreneurshipRoute:
    AcademyCoursesIcss20EntrepreneurshipRoute,
  AcademyCoursesProfessionalsAiEdgeRoute:
    AcademyCoursesProfessionalsAiEdgeRoute,
  ApiPublicPaystackVerifyRoute: ApiPublicPaystackVerifyRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
